# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Grady Hooker
description: Grady Hooker is awesome
baseurl: ""
url: "https://grady.nz"
permalink: /:categories/:year-:month-:title.html
future: true

# Pagination #
pagination:
  enabled: true
  per_page: 20
  permalink: '/page/:num/'
  title: 'Page :num of :max'
  limit: 0
  sort_field: 'circa'
  sort_reverse: true
  trail: 
    before: 2
    after: 2
    
# Auto Paging #
autopages:
  enabled: true
  categories: 
    layouts: 
      - 'autopage.html'
    title: ':cat'
    permalink: '/:cat'
  tags:
    layouts: 
      - 'autopage.html'
    title: ':tag'
    permalink: '/:tag'

# Build settings
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap

# Exclude these files from your production _site
exclude:
  - .git
  - .sass-cache
  - .editorconfig
  - .eslintignore
  - .eslintrc.js
  - _site
  - script
  - bak_files
  - Gemfile
  - Gemfile.lock
  - CNAME
